spring:
  datasource:
    url: jdbc:h2:mem:baseball
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: true
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 6000
      repositories:
        enabled: true
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
jwt:
  expiration_time: 3600000
  secret: BaseballSecretKeyBaseballSecretKey